language: generic
services:
  - docker
env:
  - PYTHON=python3.5
    DIST=ubuntu:xenial
  - PYTHON=python3.6
    DIST=ubuntu:artful

install:
  - docker pull "$DIST"
script:
  - docker run -v $PWD:/build/ -e PYTHON="$PYTHON" "$DIST" /build/ci/run.sh
